openapi: 3.0.0
info:
  version: 1.0.0
  title: ""
  description: Simple API for HME group project
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/fkadir/HMEApi/1.0.0
paths:
  /api/properties:
    get:
      summary: returns a list with the first entry the total number of pages and the rest of quick view properties includes pagination as query parameters. you can clarify the page and size of the page, default values are page=0 size=50
      parameters:
        - in: query
          name: page
          required: false
          schema:
            type: integer
        - in: query
          name: size
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: A list of QuickViewProperty objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/QuickViewProperty"
        "400":
          description: returns a 400 bad request response code (with a message)
        "500":
          description: returns a 500 internal server error. the body contains the specific error exception.
  /api/properties/{propertyId}:
    get:
      summary: returns quick view property of specific property id
      parameters:
        -in: path
        name: propertyId
        required: true
        schema:
          type: string
      responses:
        "200":
          description: returns a quickviewproperty object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuickViewProperty"
        "404":
          description: is returned when the property was not found
        "500":
          description: is returned when database access error occured
  /api/properties/details/{propertyId}:
    get:
      summary: returns details of a specific property (still placeholder data)
      parameters:
        - in: path
          name: propertyId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A DetailedPropery object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetailedProperty"
        "400":
          description: returns a 400 bad request response code (with a message)
        "404":
          description: returns a 404 not found response code
        "500":
          description: returns a 500 internal server error. the body contains the specific error exception.
    /api/properties/locations:
      get:
        summary: returns all property ids with longitude and latitude
        responses:
          "200":
            description: returns a list with objects containing property id, longitude and latitude
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
          "500":
            description: returns a list with objects containing property id, longitude and latitude
    /api/user/{id}:
      get:
      summary: returns user info for given user id
      parameters:
        - in: path
        name: id
        required: true
        schema:
        type: String
      responses:
        "200":
          description: returns user object with all their info
          content: 
            application/json:
              schema: 
              $ref: "#/components/schemas/user"
        "404":
          description: returns a 404 user not found response code
        "500":
          description: returns a 500 internal server error, the body contains the specific error
    /api/user/{id}/{resource}:
      get:
        summary: returns specific resource for specific user id 
        parameters:
          - in: path
          name: id
          required: true
          schema:
            type: String  
          - in: path
          name: resource
          required: true
          schema: 
            type: String
            example: options are w (weights), f (favourites), s (searches), a (applications) 
        responses:
          "200":
            description: returns user resources 
            content: 
              application/json:
                schema: 
                type: array 
          "400":
            description: returns 400 bad request if the type of resource is not correctly put in
          "404":
            description: returns a 404 resource not found response code
          "500":
            description: returns a 500 internal server error, the body contains the specific error
    /api/user/new/{id}/{resource}:
      post:
        summary: creates new specific resource for specific user  
        parameters:
          - in: path
          name: id
          required: true
          schema:
            type: String  
          - in: path
          name: resource
          required: true
          schema: 
            type: String
            example: options are w (weights), f (favourites), s (searches), a (applications)
          - in:  query
            name: searchString
            required: false
            schema:
              type: String
              default: ""
          - in:  query
            name: propertyId
            required: false
            schema:
              type: String
              default: ""
          - in:  query
            name: message
            required: false
            schema:
              type: String
              default: ""
          - in:  query
            name: entertainment
            required: false
            schema:
              type: String
              default: ""
          - in:  query
            name: pharmacies
            required: false
            schema:
              type: String
              default: ""
          - in:  query
            name: retail
            required: false
            schema:
              type: String
              default: ""
          - in:  query
            name: fitness
            required: false
            schema:
              type: String
              default: ""
          - in:  query
            name: financial
            required: false
            schema:
              type: String
              default: ""
          - in:  query
            name: transportation
            required: false
            schema:
              type: String
              default: ""
          - in:  query
            name: emergency
            required: false
            schema:
              type: String
              default: ""
        responses:
          "200":
            description: adds new user resource, returns 200 ok and message 
          "400":
            description: returns 400 bad request if the type of resource is not correctly put in
          "404":
            description: returns a 404 resource not found response code
          "500":
            description: returns a 500 internal server error, the body contains the specific error

  # /api/user/favourites:
  #   get:
  #     summary: retrieve all of the user's favourite properties
  #     parameters:
  #       - in: query
  #         name: userId
  #         required: true
  #         schema:
  #           type: string
  #       - in: query
  #         name: propertyId
  #         required: false
  #         schema:
  #           type: string
  #     responses:
  #       "200":
  #         description: A JSON array of QuickViewPropery objects
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: "#/components/schemas/QuickViewProperty"
  #   post:
  #     summary: create new favourite property for user
  #     parameters:
  #       - in: query
  #         name: userId
  #         required: true
  #         schema:
  #           type: string
  #       - in: query
  #         name: propertyId
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       "201":
  #         description: resource is created
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #   delete:
  #     summary: delete favourite property for user
  #     parameters:
  #       - in: query
  #         name: userId
  #         required: true
  #         schema:
  #           type: string
  #       - in: query
  #         name: propertyId
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       "200":
  #         description: returns confirmation message
  #         content:
  #           application/json:
  #             schema:
  #               type: object

  # /api/user/searches:
  #   get:
  #     summary: retrieve user's saved search(es)
  #     parameters:
  #       - in: query
  #         name: userId
  #         required: true
  #         schema:
  #           type: string
  #       - in: query
  #         name: searchId
  #         required: false
  #         schema:
  #           type: string
  #     responses:
  #       "200":
  #         description: returns a JSON array of saved searches
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: "#/components/schemas/SavedSearch"
  #   post:
  #     summary: creates a new saved search to a user's profile
  #     parameters:
  #       - in: query
  #         name: userId
  #         required: true
  #         schema:
  #           type: string
  #       - in: query
  #         name: much_more
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       "201":
  #         description: resource is created
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #   put:
  #     summary: update a user's saved search
  #     parameters:
  #       - in: query
  #         name: userId
  #         required: true
  #         schema:
  #           type: string
  #       - in: query
  #         name: searchId
  #         required: true
  #         schema:
  #           type: string
  #       - in: query
  #         name: updatedSearch
  #         required: true
  #         schema:
  #           $ref: "#/components/schemas/SavedSearch"
  #     responses:
  #       "200":
  #         description: returns confirmation message
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #   delete:
  #     summary: deletes a user's search
  #     parameters:
  #       - in: query
  #         name: userId
  #         required: true
  #         schema:
  #           type: string
  #       - in: query
  #         name: searchId
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       "200":
  #         description: returns confirmation message
  #         content:
  #           application/json:
  #             schema:
  #               type: object

components:
  schemas:
    QuickViewProperty:
      type: object
      required:
        - propertyId
        - geolocation
        - price
        - bathrooms
        - bedrooms
        - streetAddress
        - zipcode
        - description
        - images
      properties:
        id:
          type: integer
          format: int64
          example: 123456
        longitude:
          type: number
        latitude:
          type: number
        price:
          type: number
        bathrooms:
          type: integer
        bedrooms:
          type: integer
        streetAddress:
          type: string
        zipcode:
          type: string
        overview:
          type: string
        images:
          type: array
          items:
            type: string
    DetailedProperty:
      description: Details implemented right now in the mock data
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 123456
        price:
          type: number
        bedrooms:
          type: integer
        bathrooms:
          type: integer
        propertyType:
          type: string
          example: apartment
        address:
          type: string
          example: 1424 Karen Spur
        zipcode:
          type: string
        longitude:
          type: string
        latitude:
          type: string
        full_description:
          type: string
        petsAllowed:
          type: boolean
        lastUpdated:
          type: array
          items:
            type: integer
          example: [2023, 8, 30]
        datePosted:
          type: array
          items:
            type: integer
          example: [2023, 8, 30]
        TBDScore:
          type: number
        images:
          type: array
          items:
            type: string
    user:
      description: user details available in user table
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: string
        email:
          type: string
        searches:
          type: array
          items:
            type: string
        favourites:
          type: array
          items:
            type: integer
        weights:
          type: object
        applications:
          type: array
          items:
            type: object
