import PageTemplate from "./PageTemplate";
import { Paper, Box, Typography, Divider } from "@mui/material";
import YouTubeVideo from "./Youtube links/YouTubeVideo";

function FAQPage() {
	return (
		<PageTemplate
			pageTitle="Frequently Asked Questions"
			currPageBreadcrumb={"FAQ"}
		>
			<Box width={"100%"} minHeight={"60vh"}>
				<Paper elevation={3} sx={{ padding: 2 }}>
					<Box mt={5}>
						<Typography variant="h2">Using the website</Typography>
						<Divider />
						<Typography variant="body2">
							<YouTubeVideo videoId="ZIx3Ce-LA8g" />
						</Typography>
					</Box>
					<Box mt={5}>
						<Typography variant="h2">
							Information about our Scoring Systems
						</Typography>
						<Divider />
						<Typography variant="h3">Nearby Service Scores</Typography>
						<Typography variant="body2">
							The information to generate the nearby service scores is retrieved
							from Google. This information consists of multiple amenities per
							neighbourhood. The number of amenities per neighbourhood are
							standardised using z-score standardisation. This is a statistical
							technique where a score for each neighbourhood is created based on
							all of the other neighbourhood scores. We take your service
							preferences from your user profile, and use them to adapt these
							scores, so that each score is tailored to you.
						</Typography>
						<Typography variant="h3">My Match Score</Typography>
						<Typography variant="body2">
							The overall match score is generated by summing the category
							scores for each neighbourhood, and then again applying z-score
							standardisation to create a final score, where this score is
							based-off the values of each of the other overall neighbourhood
							scores.
						</Typography>
						<Typography variant="h3">Crime Safety Score</Typography>
						<Typography variant="body2">
							Similar to how the nearby service scores are calculated, the crime
							safety score takes official crime data from Open Baltimore, gets
							the count of each crime per neighbourhood, and again applies
							z-score standardisation to calculate a crime safety score which is
							based-off all of the other neighbourhood crime safety scores. The
							official data used to generate our crime safety scores can be
							found at
							<span>
								<Typography
									component={"a"}
									href="https://data.baltimorecity.gov/datasets/baltimore::part-1-crime-data/explore"
									target="_blank"
									variant="body2"
									fontWeight={800}
									color={"#05363D"}
								>
									{" Open Baltimore"}
								</Typography>
							</span>
						</Typography>
					</Box>
					<Box mt={5}>
						<Typography variant="h2">
							Information about the Tagging System
						</Typography>
						<Divider />
						<Typography variant="body2">
							The tags serve as quick indicators for users, providing valuable
							insights into the properties and their surroundings. The "Secure"
							tag informs users of low crime records in the area, the
							"Sufficient Amenities" tag highlights properties with
							above-average facilities, and the "Services" tag showcases the
							dominant local service, helping users in making informed decisions
							aligned with their preferences and priorities. Multiple services
							tag is on properties that have multiple different local services
							dominating around them. You can click on the properties to view
							more details.
						</Typography>
					</Box>
					<Box mt={5}>
						<Typography variant="h2">
							Information about Recommendation System
						</Typography>
						<Divider />
						<Typography variant="body2">
							With the properties you 'Favorite,' you provide us with valuable
							feedback about your preferences in homes or apartments. This
							feedback is instrumental in helping our recommendation system
							comprehend your unique taste in properties, enabling us to suggest
							the most suitable options for you. As you continue to 'Favorite'
							more properties, our recommender system accumulates a wealth of
							information, allowing us to make increasingly precise
							recommendations for your ideal home or apartment. Your input is
							invaluable in enhancing your property search experience.
						</Typography>
						<Typography variant="body2">
							Here at Renting Made Easy we also incorporate a second
							recommendation technology into our system architecture that uses
							User Collaborative Filtering. Click data is retrieved in order to
							find users who are most similar to you. The click data represents
							the number of times each user has clicked on each property. We
							concatenate the number of clicks per property for each user into
							patterns. Then, compare these patterns to one another to find your
							recommended users. The patterns are compared to one another using
							the cosine similarity formula. Finally, we take the most
							clicked-on properties from your most similar users and display
							them to you.
						</Typography>
					</Box>
				</Paper>
			</Box>
		</PageTemplate>
	);
}

export default FAQPage;
